- name: Import Java
  ansible.builtin.import_role:
    name: common
    tasks_from: java


- name: Maven Build
  ansible.builtin.shell: Mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app