- name: Configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-mongodb-schema.yml"
  when: schema_load
